### Signup Request
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "fullName": "testuser",
  "password": "password123",
  "email": "testuser5@example.com"
}

### Login Request
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "password123"
}

### Signout Request
POST http://localhost:3000/api/auth/signout
Content-Type: application/json

{
  "email": "testuser2@example.com"
}
